#!/usr/bin/env node

"use strict"
const fs = require('fs')

function usage() {
    console.log(`usage: ${process.argv[1]} [*mythx-api-json-path*] [*timeout-secs*]

Run MythX analyses on *mythx-api-json-path*

Set environment MYTHX_PASSWORD and one of the following:

* MYTHX_ETH_ADDRESS or
* MYTHX_EMAIL_ADDRESS

if you have have registered to reduce request rate-limiting.
`)
    process.exit(1)
}

/**********************************
  Minimal option processing
***********************************/

const argLen = process.argv.length
if (argLen === 3 &&
    process.argv[2].match(/^[-]{0,2}h(?:elp)?$/)) {
    usage()
}

// 60 seconds is a reasonable minimum timeout; For a "quick" analysis
// the backend uses a value of 30 seconds.
let timeout = 60
if (argLen >= 3 &&
    process.argv[argLen-1].match(/^\d+$/)) {
    timeout = parseInt(process.argv[argLen-1])
}


const jsonPath = process.argv[2] || `${__dirname}/sample-json/PublicArray.json`

/**********************************
  Authentication and option setup
***********************************/

let armletOptions = {
    apiKey: process.env.MYTHX_API_KEY,
    email: process.env.MYTHX_EMAIL,
    ethAddress: process.env.MYTHX_ETH_ADDRESS,
    password: process.env.MYTHX_PASSWORD,
}

if (process.env.MYTHX_ETH_ADDRESS) {
    armletOptions.ethAddress = process.env.MYTHX_ETH_ADDRESS
} else if (process.env.MYTHX_EMAIL) {
    armletOptions.email = process.env.MYTHX_EMAIL
}

/**********************************
  Example code starts here ...
***********************************/

const armlet = require('../index') // if not installed
// const armlet = require('armlet') // if installed

const client = new armlet.Client(armletOptions)

const analyzeOptions = {
    clientToolName: 'armlet-example',
    data: JSON.parse(fs.readFileSync(jsonPath, 'utf8')),
    timeout: timeout * 1000,  // convert secs to millisecs
    // client tool tracking (same as default above so really no change)
}

client.analyzeWithStatus(analyzeOptions)
    .then(result => {
        const util = require('util')
        console.log(`${util.inspect(result, {depth: null})}`)
    }).catch(err => {
        console.log(err)
    })
