#!/usr/bin/env node

"use strict"

function usage() {
    console.log(`usage: ${process.argv[1]}

Get list of prevous Mythril Platform API analyses run

Set environment variables EMAIL and MYTHRIL_API_KEY before using.
`)
    process.exit(1)
}

require('./helper')

var options = {
    apiKey: process.env.MYTHRIL_API_KEY,
    userEmail: process.env.EMAIL
}

var timeout = undefined
if (process.argv.length > 2) {
    timeout = parseInt(process.argv[3])
}

/**********************************
  Example code starts here.....
***********************************/

const armlet = require('../index') // if not installed
// const armlet = require('armlet') // if installed

const client = new armlet.Client(options)
client.listAnalyses()
    .then(result => {
        console.log(result)
    }).catch(err => {
        console.log(err)
    })
